
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="../../Origine/CSS/1_Header.css">
    <link rel="stylesheet" type="text/css" href="../../Origine/CSS/2_Main.css">
    <link rel="stylesheet" type="text/css" href="../../Origine/CSS/3_Footer.css">
    <link rel="stylesheet" type="text/css" href="../../Administrateur/Tableau_de_Bord_Admin/Tableau_de_Bord_Admin.css">
    <title>Metric Care</title>
  </head>
  <body>
    <header>
      <div id="Rectangle_Debut">
        <nav>
          <div>
            <img id="Logo" src="../../Origine/Images/Logo.png" alt="Logo Metric Metro" width="75" height="40">
            <img id="Logo_Texte" src="../../Origine/Images/Logo_texte.png" alt="Logo Metric Metro" width="200" height="50">
            <a href="https://infinitemeasures.fr/vues/fr/index.php" target="_blank">
              <img id="Logo_Infinite_Measures" src="../../Origine/Images/Infinite_logo.png" alt="Logo Infinite Measures" width="60" height="60">
            </a>
          </div>
          <div class="contenuNav">
            <a>🌐Français</a>
            <a href="../Tableau_de_Bord_Admin/Tableau_de_Bord_Admin.PHP">Tableau de bord</a>
            <a href ="../Forum/Forum.PHP">Forum</a>
            <a href ="../Gestion_des_utilisateurs/Gestion_des_utilisateurs.PHP">Gestion des utilisateurs</a>
            <a href ="../Profil_Admin/Profil_Admin.PHP">Profil</a>
          </div>
        </nav>
      </div>
    </header>
    <main>
      <div class="title">
        <h1>Tableau de bord</h1>
        <button onclick="window.location.href = '../../Administrateur/Gestion_des_utilisateurs/Gestion_des_utilisateurs.PHP';">Gestion des utilisateurs</button>
        <button onclick="window.location.href = '../../Administrateur/Profil_Admin/Profil_Admin.PHP';">Profil</button>
        <button onclick="window.location.href = '../../Administrateur/Forum/Forum.PHP';">Forum</button>
      </div>
    </main>
    <footer class="Footer">
      <div class="contenu_Footer">
        <div class="Footer_contenu_Logo">
          <img id="LogoFooter" src="../../Origine/Images/image.png" alt="Logo Metric Metro" width="80" height="80">
          <p>Metric Care © 2023 - Tous droits réservés</p>
          <a href="https://infinitemeasures.fr/vues/fr/index.php" target="_blank">
            <img id="Logo_Infinite_Measures_Footer" src="../../Origine/Images/Infinite_logo.png" alt="Logo Infinite Measures" width="60" height="60">
          </a>
        </div>
        <div class="Footer_contenu_texte">
          <a href="../CGU/CGU.PHP">CGU</a> <a>|</a>
          <a href="../AboutUs/AboutUs.PHP">À propos</a> <a>|</a>
          <a href="">Préférences des cookies</a> 
        </div>
      </div>
    </footer>
  </body>

</html>
