<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="Connexion.css"> 
    <title>Metric Care</title>
    <link rel="icon" href="Origine/Images/Logo.png">
  </head>
  <body>
    <header>
        <div>
            <img id="Logo" src="../../Origine/Images/Logo.png" alt="Logo Metric Metro", width="100", height="55"> 
            <div class="Langue">
                <a>🌐Français</a>
            </div>
        </div>  
    </header>
    <main>
        <div class="Connexion">
            <a>Connexion</a>
        </div>
        <div class="container">
            <input type="email" placeholder="Email"><br></br>
            <input type="password" placeholder="Mot de passe">
        </div>
        <div class="MDP_OUBLIE">
            <a>Mot de passe oublié ?</a>
        </div>
        <div class="rectangle-connecter">
            <a>Se Connecter</a>
        </div>
        <div class = "Pas_compte">
            <div>
                <div><a>Pas de</a></div>
                <div><a>compte ?</a></div>
            </div>
            <div class="Inscrivez-vous" href="#">
                <div><a href="Connexion.css">Inscrivez</a></div>
                <div><a href="Connexion.css">vous</a></div>
            </div>
        </div>
    </main>
  </body>
</html>