<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="../../Origine/CSS/1_Header.css">
    <link rel="stylesheet" type="text/css" href="../../Origine/CSS/3_Footer.css">
    <link rel="stylesheet" type="text/css" href="../../General/CGU/CGU.css">

    <title>Metric Care</title>
    <link rel="icon" href="Origine/Images/Logo.png">
  </head>
  <body>
    <header>
      <div id="Rectangle_Debut">
        <nav>
          <div>
            <img id="Logo" src="../../Origine/Images/Logo.png" alt="Logo Metric Metro", width="75", height="40">
            <img id="Logo_Texte" src="../../Origine/Images/Logo_texte.png" alt="Logo Metric Metro", width="200", height="50">
            <a href="https://infinitemeasures.fr/vues/fr/index.php" target="_blank">
            <img id="Logo_Infinite_Measures" src="../../Origine/Images/Infinite_logo.png" alt="Logo Infinite Measures", width="60", height="60"> </a>
          </div>      
          <div class="contenuNav">
          <a>🌐Français</a>
            <a href="../Contact/Contact.PHP">Contact</a>
            <a href="../FAQ/FAQ.PHP">FAQ</a>
            <a href="../AboutUs/AboutUs.PHP">Qui sommes nous ?</a>
            <a href="../../Authentification/Connexion/Connexion.PHP">Connexion</a>
          </div>
        </nav>
      </div>
    </header>
    <main>
    

    
      <div class="Rectangle_CGU"> 
      <a class="titre">Conditions Générales d'Utilisation (CGU)</a>
      <div class="Contenu_CGU">
        <a>Merci de lire attentivement les présentes conditions générales d'utilisation avant d'utiliser le site et les services proposés par Metric Care. En accédant ou en utilisant le site et les services, vous reconnaissez avoir lu, compris et accepté, sans limitation ni réserve, les présentes conditions générales d'utilisation. Si vous n'acceptez pas ces conditions, vous ne devez pas utiliser le site et les services proposés par Metric Care.<br><br>
        1. Objet du site et du boitier :<br><br>
        Le site propose un boitier composé de capteurs de température/humidité, sonore, CO2 et rythme cardiaque permettant de mesurer les différents paramètres de l'environnement dans lequel il est placé. Le site a pour objectif de fournir des informations précises sur ces paramètres afin d'améliorer la qualité de vie des utilisateurs.<br><br>
        2. Utilisation du site et du boitier :<br><br>
        L'utilisation du site et du boitier est soumise à l'acceptation des présentes conditions générales d'utilisation. L'utilisateur est seul responsable de l'utilisation du boitier et doit respecter les lois et réglementations en vigueur. Le site se réserve le droit de suspendre ou de résilier l'accès à tout moment si l'utilisateur ne respecte pas les présentes conditions.<br><br>
        3. Utilisation des données :<br><br>
        Le boitier collecte les données relatives aux différents paramètres environnementaux. Les données collectées seront utilisées pour fournir des informations précises aux utilisateurs. Le site s'engage à respecter la vie privée des utilisateurs et à ne pas divulguer les données collectées à des tiers sans autorisation expresse de l'utilisateur. Les données collectées seront stockées de manière sécurisée et ne seront accessibles qu'aux personnes autorisées.<br><br>
        4. Limitation de responsabilité :<br><br>
        Le site ne saurait être tenu responsable de toute perte ou dommage subi par l'utilisateur ou toute tierce partie en relation avec l'utilisation du boitier. Le site ne saurait être tenu responsable de toute interruption du service en raison de problèmes techniques ou de maintenance.<br><br>
        5. Propriété intellectuelle :<br><br>
        Le site et le boitier sont protégés par les lois sur la propriété intellectuelle. Toute utilisation non autorisée de tout ou partie du site ou du boitier peut entraîner des poursuites judiciaires.<br><br>
        6. Modification des conditions :<br><br>
        Le site se réserve le droit de modifier les présentes conditions générales d'utilisation à tout moment. Les utilisateurs seront informés des modifications via une notification sur le site ou par e-mail. Les utilisateurs doivent régulièrement vérifier les présentes conditions générales d'utilisation pour se tenir informés des éventuelles modifications.<br><br>
        Loi applicable et juridiction compétente :<br>
        Les présentes conditions générales d'utilisation sont soumises au droit français. Tout litige relatif à l'utilisation du site ou du boitier sera de la compétence exclusive des tribunaux français.
      </div></div>
    
    <div class="Menu_principal">
      <a href="../../Metric_Care.PHP"> ◂ Menu principal</a>
    </div>


    </main>
    <footer class = "Footer" >
      <div class = "contenu_Footer">
        <div class="Footer_contenu_Logo">
          <img id="LogoFooter" src="../../Origine/Images/image.png" alt="Logo Metric Metro", width="80", height="80">
          <p>Metric Care © 2023 - Tous droits réservés</p>
          <a href="https://infinitemeasures.fr/vues/fr/index.php" target="_blank">
          <img id="Logo_Infinite_Measures_Footer" src="../../Origine/Images/Infinite_logo.png" alt="Logo Infinite Measures", width="60", height="60"> </a>
        </div>
        <div class="Footer_contenu_texte">
          <a href="../../General/CGU/CGU.PHP">CGU</a> <a>|</a>
          <a href="../../General/AboutUs/AboutUs.PHP">À propos</a> <a>|</a>
          <a href="../../General/Cookies/Cookies.PHP">Préférences des cookies</a>
        </div>
      </div>
    </footer>
  </body>
</html>