<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="../../Origine/CSS/1_Header.css">
    <link rel="stylesheet" type="text/css" href="../../Origine/CSS/3_Footer.css">
    <link rel="stylesheet" type="text/css" href="../../General/CGU/CGU.css">

    <title>Metric Care</title>
    <link rel="icon" href="Origine/Images/Logo.png">
  </head>
  <body>
    <header>
      <div id="Rectangle_Debut">
        <nav>
          <div>
            <img id="Logo" src="../../Origine/Images/Logo.png" alt="Logo Metric Metro", width="75", height="40">
            <a href="../../../Metric_Care.php">
              <img id="Logo_Texte" src="../../Origine/Images/Logo_texte.png" alt="Logo Metric Metro", width="200", height="50">
            </a>
            <a href="https://infinitemeasures.fr/vues/fr/index.php" target="_blank">
            <img id="Logo_Infinite_Measures" src="../../Origine/Images/Infinite_logo.png" alt="Logo Infinite Measures", width="60", height="60"> </a>
          </div>      
          <div class="contenuNav">
          <a>🌐Français</a>
            <a href="../Contact/ContactA.PHP">Contact us</a>
            <a href="../FAQ/FAQA.PHP">FAQ</a>
            <a href="../AboutUs/AboutUs.PHP">About us</a>
            <a href="../../Authentification/Connexion/ConnectionA.php">Sing in</a>
          </div>
        </nav>
      </div>
    </header>
    <main>
    

    
      <div class="Rectangle_CGU"> 
      <a class="titre">Conditions Générales d'Utilisation (CGU)</a>
      <div class="Contenu_CGU">
        <a>Please read these terms and conditions of use carefully before using the website and services offered by Metric Care. By accessing or using the Site and Services, you acknowledge that you have read, understand and accept, without limitation or qualification, these Terms and Conditions of Use. If you do not agree to these terms and conditions, you should not use the site and services offered by Metric Care.<br><br>
        1. Purpose of the site and the box :<br><br>
        The site offers a box equipped with temperature/humidity, sound, CO2 and heart rate sensors to measure the various parameters of the environment in which it is placed. The aim of the site is to provide precise information on these parameters to improve users' quality of life.<br><br>
        2. Using the site and the box :<br><br>
        Use of the site and the box is subject to acceptance of these general conditions of use. The user is solely responsible for the use of the box and must comply with all applicable laws and regulations. The site reserves the right to suspend or terminate access at any time if the user fails to comply with these conditions.<br><br>
        3. Data usage :<br><br>
        The box collects data relating to various environmental parameters. The data collected will be used to provide accurate information to users. The site undertakes to respect users' privacy and not to divulge the data collected to third parties without the user's express authorization. The data collected will be stored securely and will only be accessible to authorized persons.<br><br>
        4. Limitation of liability :<br><br>
        The site cannot be held responsible for any loss or damage suffered by the user or any third party in connection with the use of the box. The site cannot be held responsible for any interruption of service due to technical or maintenance problems.<br><br>
        5. Intellectual property :<br><br>
        The site and the box are protected by intellectual property laws. Any unauthorized use of all or part of the site or the box may result in legal action.<br><br>
        6. Modification of conditions :<br><br>
        The site reserves the right to modify these general conditions of use at any time. Users will be informed of any changes via notification on the site or by e-mail. Users should check these terms and conditions regularly for any changes.<br><br>
        Applicable law and jurisdiction :<br>
        These terms and conditions of use are governed by French law. Any dispute relating to the use of the site or the box will be the exclusive competence of the French courts.
      </div></div>
    
    <div class="Menu_principal">
      <a href="../../Metric_Care.PHP"> ◂ Main menu</a>
    </div>


    </main>
    <footer class = "Footer" >
      <div class = "contenu_Footer">
        <div class="Footer_contenu_Logo">
          <img id="LogoFooter" src="../../Origine/Images/image.png" alt="Logo Metric Metro", width="80", height="80">
          <p>Metric Care © 2023 - All rights reserved</p>
          <a href="https://infinitemeasures.fr/vues/fr/index.php" target="_blank">
          <img id="Logo_Infinite_Measures_Footer" src="../../Origine/Images/Infinite_logo.png" alt="Logo Infinite Measures", width="60", height="60"> </a>
        </div>
        <div class="Footer_contenu_texte">
          <a href="../CGU/CGUA.PHP">GCU</a> <a>|</a>
          <a href="../AboutUs/AboutUsA.PHP">About Us</a> <a>|</a>
          <a href="../Cookies/CookiesA.PHP">Cookie preferences</a>
        </div>
      </div>
    </footer>
  </body>
</html>
