<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="../../Origine/CSS/1_Header.css">
    <link rel="stylesheet" type="text/css" href="../../Origine/CSS/2_Main.css">
    <link rel="stylesheet" type="text/css" href="../../Origine/CSS/3_Footer.css">
    <link rel="stylesheet" type="text/css" href="../../Utilisateur/Profil/Profil.css">
    <title>Metric Care</title>
  </head>
  <body>
    <header>
      <div id="Rectangle_Debut">
        <nav>
          <div>
            <img id="Logo" src="../../Origine/Images/Logo.png" alt="Logo Metric Metro" width="75" height="40">
            <img id="Logo_Texte" src="../../Origine/Images/Logo_texte.png" alt="Logo Metric Metro" width="200" height="50">
            <a href="https://infinitemeasures.fr/vues/fr/index.php" target="_blank">
              <img id="Logo_Infinite_Measures" src="../../Origine/Images/Infinite_logo.png" alt="Logo Infinite Measures" width="60" height="60">
            </a>
          </div>
          <div class="contenuNav">
            <a>🌐Français</a>
            <a>Contact</a>
            <a>FAQ</a>
            <a>Qui sommes nous ?</a>
            <a>Connexion</a>
          </div>
        </nav>
      </div>
    </header>
    <main>
      <div class="title">
        <p>Gestion de profil<p>
      </div>
      <div class="Nom">
        <div class="Intitule">
          <p>Nom<p>
        </div>
        <div class="Entrée">
          <p>DUPONT<p>
        </div>
        <div class="Editer">
          <p>Éditer<p>
        </div>
      </div>
      <div class="Prénom">
        <div class="Intitule">
          <p>Prénom<p>
        </div>
        <div class="Entrée">
          <p>Jean<p>
        </div>
        <div class="Editer">
          <p>Éditer<p>
        </div>
      </div>
      <div class="Age">
        <div class="Intitule">
          <p>Âge<p>
        </div>
        <div class="Entrée">
          <p>28 ans<p>
        </div>
        <div class="Editer">
          <p>Éditer<p>
        </div>
      </div>
      <div class="Ville">
        <div class="Intitule">
          <p>Ville<p>
        </div>
        <div class="Entrée">
          <p>Lille<p>
        </div>
        <div class="Editer">
          <p>Éditer<p>
        </div>
      </div>
      <div class="Numéro">
        <div class="Intitule">
          <p>Numéro d'identification<p>
        </div>
        <div class="Entrée">
          <p>12345678<p>
        </div>
      </div>
      <div class="Email">
        <div class="Intitule">
          <p>E-mail<p>
        </div>
        <div class="Entrée">
          <p>jean.dupont@gmail.com<p>
        </div>
        <div class="Editer">
          <p>Éditer<p>
        </div>
      </div>
      <div class="MDP">
        <div class="Intitule">
          <p>Mot de passe<p>
        </div>
        <div class="Entrée">
          <p>************<p>
        </div>
        <div class="Reinitialiser">
          <p>Réinitialiser<p>
        </div>
      </div>
      <div class="Tableau">
        <p>◂ Tableau de bord<p>
      </div>
      <div>
        <img id="Photo" src="http://localhost/Metric_Care/Metric_Care/Utilisateur/Profil/Images/photo.jpg" alt="Utilisateur" width="258" height="240">
      </div>
      <div class="Photo">
        <p>Importer une photo<p>
      </div>
      <div class="Enregistrer">
      <button onclick="window.location.href = 'http://localhost/Metric_Care/Metric_Care/Utilisateur/Capteurs/Capteurs.PHP';">Enregistrer</button>
      </div>
      <div class="Supprimer">
      <button onclick="window.location.href = 'http://localhost/Metric_Care/Metric_Care/Utilisateur/Capteurs/Capteurs.PHP';">Supprimer le compte</button>
      </div>
    </main>
    <footer class="Footer">
      <div class="contenu_Footer">
        <div class="Footer_contenu_Logo">
          <img id="LogoFooter" src="../../Origine/Images/image.png" alt="Logo Metric Metro" width="80" height="80">
          <p>Metric Care © 2023 - Tous droits réservés</p>
          <a href="https://infinitemeasures.fr/vues/fr/index.php" target="_blank">
            <img id="Logo_Infinite_Measures_Footer" src="../../Origine/Images/Infinite_logo.png" alt="Logo Infinite Measures" width="60" height="60">
          </a>
        </div>
        <div class="Footer_contenu_texte">
          <a>CGU</a> <a>|</a>
          <a>À propos</a> <a>|</a>
          <a>Préférences des cookies</a>
        </div>
      </div>
    </footer>
  </body>
</html>