<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="../../Origine/CSS/1_Header.css">
    <link rel="stylesheet" type="text/css" href="../../Origine/CSS/2_Main.css">
    <link rel="stylesheet" type="text/css" href="../../Origine/CSS/3_Footer.css">

    <link rel="stylesheet" type="text/css" href="Réinitialiser_mot_de_passe.css">

    <title>Metric Care</title>
    <link rel="icon" href="../../Origine/Images/Logo.png">
  </head>
  <body>
    <header>
      <div id="Rectangle_Debut">
        <nav>
          <div>
            <img id="Logo" src="../../Origine/Images/Logo.png" alt="Logo Metric Metro", width="75", height="40">
            <img id="Logo_Texte" src="../../Origine/Images/Logo_texte.png" alt="Logo Metric Metro", width="200", height="50">
            <a href="https://infinitemeasures.fr/vues/fr/index.php" target="_blank">
            <img id="Logo_Infinite_Measures" src="../../Origine/Images/Infinite_logo.png" alt="Logo Infinite Measures", width="60", height="60"> </a>
          </div>      
          <div class="contenuNav">
            <a>🌐Français</a>
            <a>Tableau de bord</a> <!--Gestion des données, gestion des tickets, gestion des contacts-->
            <a>Forum</a>
            <a>Profil</a>
          </div>
        </nav>
      </div>
    </header>
    <main>

        <div class="main-container">
            <h1>Réinitialisation du mot de passe</h1>
            <input type="password" id="AncienMotDePasse" name="fname" placeholder="Ancien mot de passe"><br><br>
            <input type="password" id="NouveauMotDePasse" name="fname" placeholder="Nouveau mot de passe"><br><br>
            <input type="password" id="ConfirmerMotDePasse" name="fname" placeholder="Confirmer mot de passe"><br><br>
            <button>Enregistrer</button>
        </div>
    </main>
        <footer class = "Footer">
          <div class = "contenu_Footer">
            <div class="Footer_contenu_Logo">
              <img id="LogoFooter" src="../../Origine/Images/image.png" alt="Logo Metric Metro", width="80", height="80">
              <p>Metric Care © 2023 - Tous droits réservés</p>
              <a href="https://infinitemeasures.fr/vues/fr/index.php" target="_blank">
              <img id="Logo_Infinite_Measures_Footer" src="../../Origine/Images/Infinite_logo.png" alt="Logo Infinite Measures", width="60", height="60"> </a>
            </div>
            <div class="Footer_contenu_texte">
              <a>CGU</a> <a>|</a>
              <a>À propos</a> <a>|</a>
              <a>Préférences des cookies</a>
            </div>
          </div>
        </footer>
    </body>
  </html>

