<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="../../Origine/CSS/1_Header.css">
    <link rel="stylesheet" type="text/css" href="../../Origine/CSS/3_Footer.css">
    <link rel="stylesheet" type="text/css" href="../../General/CGU/CGU.css">
    <link rel="stylesheet" type="text/css" href="../../General/AboutUs/AboutUs.css">

    <title>Metric Care</title>
    <link rel="icon" href="Origine/Images/Logo.png">
  </head>
  <body>
  <header>
      <div id="Rectangle_Debut">
        <nav>
          <div>
            <img id="Logo" src="../../Origine/Images/Logo.png" alt="Logo Metric Metro", width="75", height="40">
            <img id="Logo_Texte" src="../../Origine/Images/Logo_texte.png" alt="Logo Metric Metro", width="200", height="50">
            <a href="https://infinitemeasures.fr/vues/fr/index.php" target="_blank">
            <img id="Logo_Infinite_Measures" src="../../Origine/Images/Infinite_logo.png" alt="Logo Infinite Measures", width="60", height="60"> </a>
          </div>      
          <div class="contenuNav">
            <a>🌐Français</a>
            <a href="../Tableau_de_Bord_Admin/Tableau_de_Bord_Admin.PHP">Tableau de bord</a>
            <a href ="../Forum/Forum.PHP">Forum</a>
            <a href ="../Gestion_des_utilisateurs/Gestion_des_utilisateurs.PHP">Gestion des utilisateurs</a>
            <a href ="../Profil_Admin/Profil_Admin.PHP">Profil</a>
          </div>
        </nav>
      </div>
    </header>

    

    <main>
    

      <div class="Titre">
        <a>Qui sommes-nous ?</a>
      </div>
      <div class="Notre_Mission">
        <a>Notre mission</a>
      </div>
        <div class="Contenu_Mission">
            <a>Metric Care vise à contribuer au bien être de ses utilisateurs.
            <br><br>Nous voulons que les conducteurs et chauffeurs de métro,<br>bus et tram,
            soient dans les meilleurs conditions de travail possible.
            <br>C'est notre boîtier Metric Care qui va permettre une étude<br>de différents facteur,
            pour mettre en place par la suite des solutions.
        </div>
        <div class="Image_boitier">
            <img id="boitier" src="../../Utilisateur/AboutUs/boitier.png" alt="Boitier Metric Metro">
        </div>
      <div class="Nos_Enjeux">
        <a>Nos enjeux</a>
      </div>
      <div class="Contenu_Enjeux">
            <a>Les enjeux du boîtier Metric Metro sont portés sur l'étude
            <br>de la santé de ses utilisateurs, tout en respectant une utilisation
            <br>simple et accessible. 
            <br><br>Nous proposons donc un outil de mesure qui vise à améliorer<br>le bien être 
            ainsi que la santé des conducteurs et conductrices.
        </div>
      <div class="Femme_Volant">
            <img id="conductrice" src="../../Utilisateur/AboutUs/femme-volant.png" alt="Femme chauffeuse bus">
      </div>
    <div class="Menu_principal">
      <a href="../Tableau_de_Bord_Admin/Tableau_de_Bord_Admin.PHP"> ◂ Tableau de bord</a>


    </main>


    <footer class = "Footer">
      <div class = "contenu_Footer">
        <div class="Footer_contenu_Logo">
          <img id="LogoFooter" src="../../Origine/Images/image.png" alt="Logo Metric Metro", width="80", height="80">
          <p>Metric Care © 2023 - Tous droits réservés</p>
          <a href="https://infinitemeasures.fr/vues/fr/index.php" target="_blank">
          <img id="Logo_Infinite_Measures_Footer" src="../../Origine/Images/Infinite_logo.png" alt="Logo Infinite Measures", width="60", height="60"> </a>
        </div>
        <div class="Footer_contenu_texte">
        <div class="Footer_contenu_texte">
          <a href="../../Administrateur/CGU/CGU.PHP">CGU</a> <a>|</a>
          <a href="../../Adlinistrateur/AboutUs/AboutUs.PHP">À propos</a> <a>|</a>
          <a >Préférences des cookies</a>
        </div>
        </div>
      </div>
    </footer>
  </body>
</html>
